spring:
  application:
    name: S3ParseService
  lifecycle:
    timeout-per-shutdown-phase: 20s
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    template:
      default-topic: input

  data:
    mongodb:
      host: localhost
      port: 27017
      database: CourseworkDB

server:
  port: 9300
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

kafka:
  consumer:
    group-id: s3Group
    auto-commit: true
    offset-reset: earliest
    session-timeout: 6000
    auto-commit-interval: 100
    concurrency: 3

  producer:
    retries: 0
    batch-size: 4096
    linger: 1
    buffer-memory: 40960

  s3-topic:
    name: s3Topic
    partitions: 3

  nlp-topic:
    name: nlpTopic
    partitions: 3
    replication-factor: 1

minio:
  url: http://127.0.0.1:9000
  access-key: alexander
  secret-key: 18520655Minio
  bucket-name: my-bucket
